import { Outfit } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";

const outfitSans = Outfit({
  variable: "--font-outfit-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const outfitMono = Outfit({
  variable: "font-outfit-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Blog App with MongoDB",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${outfitSans.variable} ${outfitMono.variable} antialiased`}
      >
        {children}
        <Footer/>
      </body>
    </html>
  );
}
